// server/services/jussi/generateDailySummary.js - Jussi Daily Summary Generator
import { PrismaClient } from '@prisma/client';
import { processReceiptAnalytics } from '../analytics/processReceiptData.js';

const prisma = new PrismaClient();

async function generateDailySummary() {
  try {
    console.log('🤖 Jussi Daily Summary Generator');
    console.log('===============================');

    // Get restaurant info
    const restaurant = await prisma.restaurant.findFirst();
    if (!restaurant) {
      console.log('❌ No restaurant found in database');
      return;
    }

    console.log(`📍 Restaurant: ${restaurant.name}`);

    // Process analytics
    const analytics = await processReceiptAnalytics();
    
    // Generate Jussi's AI summary
    const summary = generateJussiSummary(restaurant, analytics);
    
    // Create job record
    await prisma.job.create({
      data: {
        restaurantId: restaurant.id,
        type: 'EMAIL_SUMMARY',
        status: 'SUCCESS',
        payload: {
          restaurantId: restaurant.id,
          date: new Date().toISOString(),
          totalRevenue: analytics.totals.revenue,
          receipts: analytics.totals.receipts,
          topItems: analytics.topItemsByQty.slice(0, 3),
          summary: summary
        }
      }
    });

    console.log('\\n📧 EMAIL SUMMARY (Preview):');
    console.log('============================');
    console.log(summary);

    console.log('\\n✅ Daily summary generated and job record created');
    
    return { restaurant, analytics, summary };

  } catch (error) {
    console.error('❌ Daily summary generation failed:', error);
    
    // Log failed job
    try {
      const restaurant = await prisma.restaurant.findFirst();
      if (restaurant) {
        await prisma.job.create({
          data: {
            restaurantId: restaurant.id,
            type: 'EMAIL_SUMMARY', 
            status: 'FAILED',
            payload: { error: error.message }
          }
        });
      }
    } catch (jobError) {
      console.error('Failed to log error job:', jobError);
    }
    
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

function generateJussiSummary(restaurant, analytics) {
  const lines = [];
  
  lines.push('🤖 Jussi — Daily Operations Report');
  lines.push(`📍 ${restaurant.name}`);
  lines.push(`📅 ${new Date().toLocaleDateString('en-GB')} (Generated: ${new Date().toLocaleTimeString('en-GB')})`);
  lines.push('');
  
  lines.push('📊 SALES PERFORMANCE');
  lines.push('==================');
  lines.push(`💰 Total Revenue: ฿${(analytics.totals.revenue / 100).toFixed(2)}`);
  lines.push(`📋 Total Orders: ${analytics.totals.receipts}`);
  lines.push(`🎯 Average Ticket: ฿${(analytics.totals.averageTicket / 100).toFixed(2)}`);
  lines.push('');
  
  lines.push('💳 PAYMENT METHODS');
  lines.push('=================');
  Object.entries(analytics.paymentBreakdown).forEach(([method, amount]) => {
    if (amount > 0) {
      const percentage = ((amount / analytics.totals.revenue) * 100).toFixed(1);
      lines.push(`${getPaymentIcon(method)} ${method}: ฿${(amount / 100).toFixed(2)} (${percentage}%)`);
    }
  });
  lines.push('');
  
  lines.push('🏆 TOP PERFORMING ITEMS');
  lines.push('======================');
  analytics.topItemsByQty.slice(0, 5).forEach((item, i) => {
    lines.push(`${i + 1}. ${item.name}`);
    lines.push(`   📦 Quantity: ${item.qty} units`);
    lines.push(`   💰 Revenue: ฿${(item.revenue / 100).toFixed(2)}`);
    lines.push('');
  });
  
  lines.push('📈 INSIGHTS & RECOMMENDATIONS');
  lines.push('=============================');
  
  // Generate insights based on data
  const insights = generateInsights(analytics);
  insights.forEach(insight => lines.push(`• ${insight}`));
  
  lines.push('');
  lines.push('🔧 NEXT ACTIONS');
  lines.push('==============');
  lines.push('• Monitor inventory levels for top-selling items');
  lines.push('• Ensure adequate staffing for peak hours');
  lines.push('• Review payment processing efficiency');
  lines.push('• Update menu pricing based on performance data');
  
  lines.push('');
  lines.push('---');
  lines.push('Generated by Jussi AI Analytics System');
  lines.push(`Data from ${analytics.period.start} to ${analytics.period.end}`);
  
  return lines.join('\\n');
}

function getPaymentIcon(method) {
  const icons = {
    CASH: '💵',
    CARD: '💳', 
    QR: '📱',
    OTHER: '🔄'
  };
  return icons[method] || '💰';
}

function generateInsights(analytics) {
  const insights = [];
  
  // Revenue insights
  if (analytics.totals.averageTicket > 40000) { // 400 THB
    insights.push('Strong average ticket value indicates premium positioning is working');
  } else if (analytics.totals.averageTicket < 20000) { // 200 THB
    insights.push('Consider upselling strategies to increase average ticket value');
  }
  
  // Payment method insights
  const totalPayments = Object.values(analytics.paymentBreakdown).reduce((a, b) => a + b, 0);
  const cashPercentage = (analytics.paymentBreakdown.CASH / totalPayments) * 100;
  
  if (cashPercentage > 50) {
    insights.push('High cash usage detected - ensure adequate change management');
  } else if (cashPercentage < 20) {
    insights.push('Digital payment adoption is strong - consider digital loyalty programs');
  }
  
  // Top item insights
  if (analytics.topItemsByQty.length > 0) {
    const topItem = analytics.topItemsByQty[0];
    insights.push(`"${topItem.name}" is your star performer with ${topItem.qty} sales`);
  }
  
  // Daily performance insights
  if (analytics.dailyBreakdown.length > 1) {
    const sortedDays = analytics.dailyBreakdown.sort((a, b) => b.revenue - a.revenue);
    const bestDay = sortedDays[0];
    insights.push(`Best performing day: ${bestDay.date} with ฿${(bestDay.revenue / 100).toFixed(2)} revenue`);
  }
  
  return insights;
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  generateDailySummary()
    .then(() => {
      process.exit(0);
    })
    .catch((error) => {
      console.error('Failed to generate daily summary:', error);
      process.exit(1);
    });
}

export { generateDailySummary };